First Attempt at Win GUI Build
Environment setup OK.

But compile fails with errors about converting <windows.h> types to <windows.h> types ... or what?

For example:
Error C2664:
'HWND CreateDialogParamA(HINSTANCE,
                                                LPCSTR,
                                                HWND,
                                                DLGPROC,
                                                LPARAM)':
 cannot convert argument 4 from
       'BOOL (__cdecl *)(HWND,UINT,WPARAM,LPARAM)'
 to
      'DLGPROC'

Um ... OK ... why not?  I guess even the Win API has changed in 27 years.